{
 "title": "MySQL Server Dash Board",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Queries Rate",
   "type": "graph",
   "description": "Count of All Queries run (select, insert, update, etc,)",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_queries[1m])",
     "legendFormat": "Queries Per Minute"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "description": "Display Current Active connections",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "gauge",
   "description": "Display Maximum Connections",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Max Used Connections"
    }
   ]
  },
  { "title": "Alerts List", "type": "alertlist", "gridPos": { "h": 7, "w": 6, "x": 17, "y": 7 } }
 ]
}