{
 "title": "Yabeda Sidekiq",
 "description": "Example dashboard for metrics provided by yabeda-sidekiq gem for monitoring Sidekiq: simple and efficient background processing solution for Ruby.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Jobs processed every second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total[1m]))",
     "legendFormat": "Successful jobs"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total[1m]))",
     "legendFormat": "Failed jobs"
    }
   ]
  },
  {
   "title": "Jobs processed by queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total[1m])) by (queue)",
     "legendFormat": "Processed in {{queue}}"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total[1m])) by (queue)",
     "legendFormat": "Failed in {{queue}}"
    }
   ]
  },
  {
   "title": "Jobs processed by job type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total[1m])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Queue sizes",
   "type": "graph",
   "description": "Number of jobs waiting in queues to be executed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_jobs_waiting_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Queue latencies",
   "type": "graph",
   "description": "Queue latency is the difference in seconds since the oldest job in the queue was enqueued. Or how long job is waiting its turn to be executed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_queue_latency) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Job processing average time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_job_runtime_seconds_bucket[1m])) by (le)) ",
     "legendFormat": "95% quantile of sidekiq "
    }
   ]
  },
  {
   "title": "Job processing average time by job type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_job_runtime_seconds_bucket[1m])) by (worker, le)) ",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Sidekiq jobs pushed by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_enqueued_total[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Retry set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(sidekiq_jobs_retry_count)", "legendFormat": "{{queue}}" }
   ]
  }
 ]
}